name: Go

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.17.6'

      - name: mkdir dist
        run: mkdir dist

      - name: Build
        run: go build -ldflags="-s -w" -o ./dist/battery-linux-amd64 ./cmd/battery/main.go
      - name: Build
        run: go build -ldflags="-s -w" -o ./dist/disk-linux-amd64 ./cmd/disk/main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/battery-linux-amd64
            dist/disk-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
