name: Go

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build
        run: go build -v ./...

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          platforms: 'linux/amd64'
          package: ''
          name: 'battery'
          compress: 'false'
          dest: 'dist'

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/battery-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
